### ISSUE TITLE
Using Chrome DevTools to debug frontend

### ISSUE THREAD

**Issue by hoangnh40** [mikechabot/react-boilerplate#17]
I need to configure it to be able to use Chrome DevTools  debugging frontend. Currently webpack has been compressed by these files. Help me !

**Comment by andrewsantarin** [comment]
I haven't used this boilerplate in a long time, but have you tried [`devtool: 'source-map'`](https://stackoverflow.com/a/31101665)? More options listed on [the official Webpack documentation](https://webpack.js.org/configuration/devtool/).

Adjust here:
https://github.com/mikechabot/react-boilerplate/blob/dc25c21cec94d0a0a9e9ae2d6ad6456546723072/webpack.config.js#L163

**Comment by hoangnh40** [comment]
> I haven't used this boilerplate in a long time, but have you tried [`devtool: 'source-map'`](https://stackoverflow.com/a/31101665)? More options listed on [the official Webpack documentation](https://webpack.js.org/configuration/devtool/).
> 
> Adjust here:
> https://github.com/mikechabot/react-boilerplate/blob/dc25c21cec94d0a0a9e9ae2d6ad6456546723072/webpack.config.js#L163

tks u @andrewsantarin ! It worked !
